dist: xenial
language: python
python:
  - '3.7'
before_install:
  - pip install poetry
install:
  - make install
script:
  - make build
deploy:
  - provider: releases
    api_key: '$GITHUB_TOKEN'
    file_glob: true
    file: './dist/*'
    skip_cleanup: true
    name: favink $TRAVIS_TAG - build $TRAVIS_BUILD_NUMBER
    on:
      tags: true
  - provider: script
    script: poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD
    skip_cleanup: true
    on:
      tags: true
