dist: xenial
language: python
python:
  - "3.7"
before_install:
  - pip install poetry
install:
  - make install
script:
  - make check-code || travis_terminate 1;
  - make test || travis_terminate 1;
  - make build